name: Build iOS IPA
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          # On ajoute 'cython' ici pour que GitHub l'installe
          pip install buildozer kivy-ios cython
      - name: Build IPA
        run: |
          buildozer ios debug
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MonApp-iOS
          path: bin/*.ipa